import './sass/main.scss';
import './JS/bg';
import './JS/footer';
import './JS/header';
import './JS/input';
import './JS/modal';
import './JS/input';
import './templates/markup.hbs'
import './templates/modal.hbs.hbs'
